version: '3.8'

services:
  comment-db:
    image: postgres
    container_name: comment-service-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - comment_db_data:/var/lib/postgresql/data
    networks:
      - comment-network

  comment-service:
    build: .
    container_name: comment-service-app
    restart: unless-stopped
    ports:
      - "${USER_SERVICE_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: jdbc:postgresql://comment-db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

    depends_on:
      - comment-db
    networks:
      - comment-network
      - shared-network

networks:
  comment-network:
    driver: bridge
  shared-network:
    driver: bridge
    external: true
    name: shared-network

volumes:
  comment_db_data: